"use client";

import ReactMarkdown from "react-markdown";

export default function DocumentViewer({ content }: { content: string }) {
  return (
    <div className="flex justify-center bg-gray-800 p-10">

      {/* A4 PAGE */}

      <div
        className="bg-white text-black shadow-lg"
        style={{
          width: "794px",
          minHeight: "1123px",
          padding: "80px",
          position: "relative"
        }}
      >

        {/* HEADER */}

        <div
          style={{
            position: "absolute",
            top: "30px",
            left: "80px",
            right: "80px",
            display: "flex",
            justifyContent: "space-between",
            fontSize: "12px",
            color: "#555"
          }}
        >
          <span>LegalFormat</span>
          <span>Rent Agreement</span>
        </div>

        {/* DOCUMENT CONTENT */}

        <div className="prose max-w-none">

          <ReactMarkdown
            components={{
              h1: ({node, ...props}) => (
                <h1 className="text-center text-2xl font-bold mb-6" {...props} />
              ),
              h2: ({node, ...props}) => (
                <h2 className="text-lg font-bold mt-6 mb-2" {...props} />
              ),
              p: ({node, ...props}) => (
                <p className="mb-3 leading-relaxed text-sm" {...props} />
              )
            }}
          >
            {content}
          </ReactMarkdown>

        </div>

        {/* FOOTER */}

        <div
          style={{
            position: "absolute",
            bottom: "30px",
            left: "80px",
            right: "80px",
            display: "flex",
            justifyContent: "space-between",
            fontSize: "12px",
            color: "#555"
          }}
        >
          <span>Generated by LegalFormat</span>
          <span>Page 1</span>
        </div>

      </div>
    </div>
  );
}
