
"use client";

import { useState } from "react";

export default function RentAgreementPage() {

  const [landlord, setLandlord] = useState("");
  const [tenant, setTenant] = useState("");
  const [rent, setRent] = useState("");
  const [agreement, setAgreement] = useState("");

  const generateAgreement = () => {

    const text = `
RENT AGREEMENT

This Rent Agreement is made between:

Landlord: ${landlord}
Tenant: ${tenant}

Monthly Rent: ₹${rent}

Both parties agree to the terms of the rental agreement.

Generated by LegalFormat
`;

    setAgreement(text);

  };

  const startPayment = async () => {

    const res = await fetch("/api/create-checkout-session", {
      method: "POST"
    });

    const data = await res.json();

    if (data.url) {
      window.location.href = data.url;
    } else {
      alert("Stripe checkout failed");
    }

  };

  return (

    <main className="min-h-screen bg-[#020617] text-white flex flex-col items-center pt-20">

      <h1 className="text-4xl font-bold mb-10">
        Rent Agreement Generator
      </h1>

      {/* FORM */}

      <div className="flex flex-col gap-4 w-[400px]">

        <input
          placeholder="Landlord Name"
          className="p-3 rounded bg-gray-800"
          onChange={(e)=>setLandlord(e.target.value)}
        />

        <input
          placeholder="Tenant Name"
          className="p-3 rounded bg-gray-800"
          onChange={(e)=>setTenant(e.target.value)}
        />

        <input
          placeholder="Monthly Rent"
          className="p-3 rounded bg-gray-800"
          onChange={(e)=>setRent(e.target.value)}
        />

        <button
          onClick={generateAgreement}
          className="bg-purple-600 py-3 rounded-lg"
        >
          Generate Agreement
        </button>

      </div>

      {/* PREVIEW */}

      {agreement && (

        <div className="mt-10 bg-gray-900 p-6 rounded-lg w-[600px]">

          <pre className="whitespace-pre-wrap">
            {agreement}
          </pre>

          <button
            onClick={startPayment}
            className="bg-purple-600 mt-6 px-6 py-3 rounded-lg"
          >
            Pay ₹10 & Download
          </button>

        </div>

      )}

    </main>

  );

}

